[theme]
background = "dark"
primary = "light white"
secundary = "#076678"
title = "light white"
playing = "white"
playing_selected = "black"
playing_bg = "#586e75"
highlight = "white"
highlight_bg = "#586e75"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#586e75"
statusbar_bg = "#586e75"
cmdline = "#586e75"
cmdline_bg = "black"
search_match = "light red"
